// Cosmos entry point
import React, { Component } from 'react';
import { CosmosNativeLoader } from 'react-cosmos-loader/native';
// cosmos.modules can be missing before it's generated by cosmos-native cmd
// eslint-disable-next-line import/no-unresolved
import { options, getUserModules } from './tools/cosmos/cosmos.modules';

export default class App extends Component {
  render() {
    return <CosmosNativeLoader options={options} modules={getUserModules()} />;
  }
}
